//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_User
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Package
    {
        public tbl_Package()
        {
            this.tbl_FeaturedPackage = new HashSet<tbl_FeaturedPackage>();
            this.tbl_Gallery = new HashSet<tbl_Gallery>();
            this.tbl_PlacePackage = new HashSet<tbl_PlacePackage>();
            this.tbl_Price = new HashSet<tbl_Price>();
        }
    
        public int pkg_ID { get; set; }
        public string pkf_Name { get; set; }
        public string pkg_Subtitle { get; set; }
        public string pkg_Overview { get; set; }
        public string pkg_Description { get; set; }
        public string pkg_Inclusion { get; set; }
        public Nullable<bool> pkg_DefaultSeason { get; set; }
        public string pkg_DefaultRoom { get; set; }
        public string pkg_DefaultDay { get; set; }
        public string pkg_DayHeading1 { get; set; }
        public string pkg_DayItinerary1 { get; set; }
        public string pkg_DayHeading2 { get; set; }
        public string pkg_DayItinerary2 { get; set; }
        public string pkg_DayHeading3 { get; set; }
        public string pkg_DayItinerary3 { get; set; }
        public string pkg_Roomtype1 { get; set; }
        public string pkg_Roomtype2 { get; set; }
        public string pkg_Roomtype3 { get; set; }
        public Nullable<int> pkg_Priority { get; set; }
        public Nullable<bool> pkg_Active { get; set; }
        public string pkg_BannerImage { get; set; }
        public string pkg_SquareImage { get; set; }
        public string pkg_BackgroundImage1 { get; set; }
        public string pkg_BackgroundImage2 { get; set; }
        public Nullable<int> pkg_ExclusionFK { get; set; }
        public Nullable<int> pkg_TermsAndConditionFK { get; set; }
        public Nullable<int> pkg_CancelPolicyFK { get; set; }
        public Nullable<int> pkg_SubcategoryFK { get; set; }
    
        public virtual tbl_CancelPolicy tbl_CancelPolicy { get; set; }
        public virtual tbl_Exclusion tbl_Exclusion { get; set; }
        public virtual ICollection<tbl_FeaturedPackage> tbl_FeaturedPackage { get; set; }
        public virtual ICollection<tbl_Gallery> tbl_Gallery { get; set; }
        public virtual tbl_Subcategory tbl_Subcategory { get; set; }
        public virtual tbl_TermsAndCondition tbl_TermsAndCondition { get; set; }
        public virtual ICollection<tbl_PlacePackage> tbl_PlacePackage { get; set; }
        public virtual ICollection<tbl_Price> tbl_Price { get; set; }
    }
}
