//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_User
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Subcategory
    {
        public tbl_Subcategory()
        {
            this.tbl_Package = new HashSet<tbl_Package>();
        }
    
        public int sct_ID { get; set; }
        public string sct_Name { get; set; }
        public Nullable<int> sct_CategoryFK { get; set; }
        public string sct_Descripton { get; set; }
        public Nullable<int> sct_Priority { get; set; }
        public Nullable<bool> sct_Active { get; set; }
        public string sct_BannerImage { get; set; }
        public string sct_SquareImage { get; set; }
        public string sct_BackgroundImage1 { get; set; }
        public string sct_BackgroundImage2 { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual ICollection<tbl_Package> tbl_Package { get; set; }
    }
}
